MAIN/urls.py
from django.urls import path

from . import views

app_name = "Produs"

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('brands/', views.BrandsList.as_view(), name='brands'),
    path('cautare_avansata/', views.produs_list, name='avansata'),
]

URBAN_SHOES/urls.py
from django import views
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from MAIN.views import BrandsList

urlpatterns = [
    path('', include('MAIN.urls')),
    path('log_in/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path(r'', include('django.contrib.auth.urls'), {'next_page': 'login'}, name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path(r'', include('carts.urls')),
    path('', BrandsList.as_view()),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from . import views
from .views import view_cart, add_to_cart, orders, CartUpdateView, remove_from_cart, ComenziList

app_name = "carts"

urlpatterns = [
    path('cos/', view_cart, name='cos'),
    path('cart/', add_to_cart, name='cart'),
    path('order/', orders, name='order'),
    path('history/<int:pk>/', CartUpdateView.as_view(), name='OrderUpdate'),
    path('remove/<int:pk>/', remove_from_cart, name='remove'),
    path('istoric/', ComenziList.as_view(), name='IstoricComenzi'),
]

templates/cos_produse/cos.html
{% extends 'base.html' %}


{% block content %}
<head>
    <style>
    .center {
      margin-left: auto;
      margin-right: auto;
    }

    #top{
    height:100px;
    }

    .center-btn {
  display: flex;
  justify-content: center;
  align-items: center;
}




    </style>
</head>

<body>
<br><br><br><br><br><br>
<div>
    <div class="tabel" style="display: flex; justify-content: center;">
    {% if 'history' in request.path %}
        <table id='disp' style=" text-align:center ">
            <tr>
                <td class="spaceUnder" style="padding-bottom: 20px;"><h2>Comanda dvs a fost inregistrata cu succes.</h2></td>
            </tr>
            <tr>
                <td><h4 style="padding-bottom: 30px">Suma totala de plata pentru aceasta comanda: {{ total }} lei</h4></td>
            </tr>
        </table>
    </div>
    {% endif %}
</div>


    <div class="center-btn">
        <table width="800px" border="3" class="center">
            {% for item in cart %}
            <tr>
                <td>
                    <img src="{{ item.produse.img.url }}" height=150px width=170px>
                    {{ item.produse.brand }} - {{ item.produse.pret }} RON
                    {% if 'history' not in request.path %}
                    <button type="submit" class="btn btn-outline-dark btn-sm"
                            style="width:120px; text-align:center; float:right; margin-top: 60px; margin-right: 5px">
                        <a href="{% url 'carts:remove' item.id %}">Sterge din cos</a>
                    </button>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <br><br>
    <div class="button">
        {% if 'history' not in request.path %}
            {% if cart %}
            <div class="center-btn">
                <h4 style="float:left">Total plata: {{ pret_total }} lei &nbsp;&nbsp;</h4>
                <button type="button" class="btn btn-outline-dark btn-lg"
                        style="width:200px; text-align:center;"
                        onclick="window.location.href = '{% url 'carts:order' %}'">Confirma comanda
                </button>
            </div>
            {% else %}
            <div class="center-btn">
                <a title="Te rugam sa adaugi produse in cos pentru a finaliza comanda"
                   class="btn btn-outline-dark btn-lg disabled" style="width:200px; text-align:center">Confirma comanda</a>
            </div>
            {% endif %}
        {% else %}
            <div class="center-btn" style="float:left; margin-left:90px">
                <button type="button" class="btn btn-outline-dark" style="width:220px; text-align:center"
                    onclick="window.location.href = '{% url 'Produs:home' %}'">Inapoi la prima pagina
                </button>
            </div>
            <div class="center-btn" style="float:right; margin-right:90px">
                <button type="button" class="btn btn-outline-dark " style="width:220px; text-align:center"
                    onclick="window.location.href = '{% url 'carts:IstoricComenzi' %}'">Vizualizare istoric comenzi
                </button>
            </div>
        {% endif %}
    </div>
</body>
{% endblock %}

templates/cos_produse/istoric.html
{% extends 'base.html' %}


{% block content %}
<head>
    <style>

    #top{
    height:100px;
    }

    </style>
</head>
<body>
{% if request.user.is_authenticated %}
<h1 style="text-align:center; margin-top: 100px">Istoric Comenzi</h1>
<ul>
{% for item in object_list %}
    <li>
       <button type="button" class="btn btn-outline-dark btn-lg"
               style="width: 50px; text-align: center; margin-bottom: 10px"
               onclick="location.href='/history/{{ item.id }}'">{{ item.nr_comanda }}
       </button>  &nbsp; {{ item.data_finalizare_comanda }}
    </li>
{% empty %}
    <li style="margin-top:100px; margin-left:30px">Nu aveti comenzi inregistrate.</li>
{% endfor %}
</ul>
{% endif %}
</body>

{% endblock %}

templates/cos_produse/order.html
{% extends 'base.html' %}


{% block content %}
<head>
    <style>

        #top{
    height:100px;
    }

        #disp {
	margin-top: 150px;
	padding-top: 150px;
	margin-bottom: 100px;
	padding-bottom: 100px;
	width: 100%;
	}
    </style>
</head>
<body>
<pre></pre><br>
<div class="tabel" style="display: flex; justify-content: center;">
    <table id='disp'style=" text-align:center ">
        <tr>
            <td class="spaceUnder" style="padding-bottom: 20px;"><h2>Comanda dvs a fost inregistrata cu succes.</h2></td>
            <br>
        </tr>
        <tr>
            <td><h4>Suma totala de plata pentru aceasta comanda este de {{ order.total }} lei</h4></td>
            <br>
        </tr>
        <br>
    </table>
</div>
</body>

{% endblock %}