MAIN/urls.py
from django.urls import path

from . import views

app_name = "Produs"

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('brands/', views.BrandsList.as_view(), name='brands'),
    path('cautare_avansata/', views.produs_list, name='avansata'),
]

URBAN_SHOES/urls.py
from django import views
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from MAIN.views import BrandsList

urlpatterns = [
    path('', include('MAIN.urls')),
    path('log_in/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path(r'', include('django.contrib.auth.urls'), {'next_page': 'login'}, name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path(r'', include('carts.urls')),
    path('', BrandsList.as_view()),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django import views
from django.urls import path

from contact.views import suport, contact, date_personale


app_name = "contact"

urlpatterns = [
    path('suport/', suport, name='suport'),
    path('contact/', contact, name='contact'),
    path('contact/date_caracter_personal/', date_personale, name='date'),
]

contact/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.


class Formular(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    telefon_regex = RegexValidator(regex=r'^\+?1?\d{9,10}$', message="Numarul de telefon trebuie introdus in formatul: '+0799999999'.")
    telefon = models.CharField(validators=[telefon_regex], max_length=10, blank=True)
    email = models.EmailField()
    titlu = models.CharField(max_length=200)

contact/forms.py
from django import forms
from django.forms import TextInput, NumberInput, CheckboxInput

from contact.models import Formular


class ContactForm(forms.ModelForm):
    comentariu = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = Formular
        fields = ['first_name', 'last_name', 'telefon', 'email', 'titlu', 'comentariu']

        widgets = {
            'first_name': TextInput(attrs={'placeholder': 'Prenume', 'class': 'form-control'}),
            'last_name': TextInput(attrs={'placeholder': 'Nume', 'class': 'form-control'}),
            'telefon': NumberInput(attrs={'placeholder': 'Telefon', 'class': 'form-control'}),
            'email': TextInput(attrs={'placeholder': 'Email', 'class': 'form-control'}),
            'titlu': TextInput(attrs={'placeholder': 'Titlul mesajului', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['comentariu'].widget.attrs['placeholder'] = 'Adaugati un comentariu'
        self.fields['comentariu'].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        telefon = cleaned_data.get('telefon')
        email = cleaned_data.get('email')
        titlu = cleaned_data.get('titlu')
        comentariu = cleaned_data.get('comentariu')
        # telefon_exists = None
        # if telefon_exists:
        #     telefon_invalid = "Numarul de telefon trebuie introdus in formatul:'+0799999999'"
        #     self.errors['telefon'] = self.error_class([telefon_invalid])
        return cleaned_data

contact/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from contact.forms import ContactForm
from django.views.generic import CreateView

from contact.models import Formular


def suport(request):
    return render(request, "contact/suport.html", None)


def date_personale(request):
    return render(request, "contact/date_caracter_personal.html", None)


class CreateFormular(CreateView):
    form_class = ContactForm
    model = Formular
    template_name = 'contact/contact.html'


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data.get('first_name', '')
            last_name = form.cleaned_data.get('last_name', '')
            telefon = form.cleaned_data.get('telefon', '')
            from_email = form.cleaned_data.get('email', '')
            subject = form.cleaned_data.get('titlu', '')
            message = form.cleaned_data.get('comentariu', '')
            try:
                send_mail(
                    subject,
                    message,
                    from_email,
                    # first_name,
                    # last_name,
                    # telefon,
                    # titlu,
                    ['shoesurbangear@gmail.com'],
                )
            except BadHeaderError:
                    return HttpResponse('Camp invalid')
            return render(request, "contact/succes.html", None)
    return render(request, "contact/contact.html", {'form': form})

templates/contact/contact.html
{% extends 'base.html' %}
{% block content %}

<head>
    <style>

    #top{
    height:1350px;
    }

     #map {
    width: 100%;
    height: 345px;
    background-color: grey;
    }

    .col-md-3 {width: 25%; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float:left}
    .col-md-9 {width: 75%; position: relative; min-height: 1px; padding-left: 60px; float:left; color:white}

    .form-contact {width: 25%; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float:left}
    #form-mesaj {width: 75%; position: relative; min-height: 1px; padding-left: 60px; float:left; color:white}
    #coment {width: 75%; position: relative; min-height: 1px; height: 260px; padding-left: 15px;
    float:left; overflow: hidden; left: 45px; width: 690px; margin-top: 0px; margin-bottom: 0px;}
    .errorlist {color:white}


    </style>
</head>

<body>
<div class="description" style="text-align:center; color:white"><br><br>
    <p>Dragi clienti, incercam sa raspundem cat mai prompt tuturor solicitarilor.</p>

    <p>In cazul in care aveti orice fel de nelamurire va rugam sa consultati mai intai pagina&nbsp;<a
            href="{% url 'contact:suport' %}">https://www.urbangear.ro/suport</a></p><br>
    <hr style="height:2px;border-width:0;color:gray;background-color:white">
    <br><br>
</div>

<div class="col-md-3" style="color:white">
    <h3 class="pinktitle">CONTACT</h3>
    <p><strong>SC URBAN SHOES SRL</strong><br>
    <p>CUI RO12345678<br>
        J40/1234/2020</p>
    <p><strong>Adresa contact:</strong><br>
    <p>Str. Martisor Nr. 22 - Sector 4<br>
        Cod Poștal 041242 – București<br>
        Tel.: 031 225 25 25<br>
        Fax.: 031 225 25 25</p>
    <p><a href="{% url 'Produs:home' %}">www.urbangear.ro</a>
        contact@urbangear.ro</p>
    <!--    <h3 class="pinktitle">Call Center</h3>-->
    <!--    <p><strong>Program call center:</strong><br>-->
    <!--    <p>Luni - Vineri: 08:00 – 21:00<br>-->
    <!--       Sambata: 08:00 – 17:00-->
    <!--       Duminica: Indisponibil</p>-->
</div>

<div class="col-md-9">
    <div id="map"></div>
    <br><br><br><br>
</div>

<div class="contact">
    <h4 style="text-align:center; color:white">Vrei sa faci o sesizare?</h4><br>
    <div class="control" style="backgound-color:#f000">
        <form method="POST">
            {% csrf_token %}
            <div class="form-contact" style="color:white">
                <p>{{ form.first_name }}<br></p>
                <p>{{ form.last_name }}<br></p>
                <p>{{ form.telefon }}<br></p>
                <p>{{ form.email }}<br></p>
                <button type="submit" class="btn btn-info" style="margin-left: 50px">Trimite mesaj</button>
            </div>
            <p id="form-mesaj">{{ form.titlu }}<br></p>
            <p id="coment">{{ form.comentariu }}<br><br></p>
            {{ form.errors }}
        </form>
    </div>
</div><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<div class="col-md-10">
        <p class="contactext" style="color:white">Prelucrarea Datelor Personale*:<br><br>
            <span class="wpcf7-form-control-wrap date-personale"><span
                    class="wpcf7-form-control wpcf7-checkbox wpcf7-validates-as-required date-personale"><span
                    class="wpcf7-list-item first last"><label><input type="checkbox"
                                                                     name="date-personale[]"
                                                                     value="Sunt de acord cu prelucrarea datelor cu caracter personal, în conformitate cu prevederile Legii 677/2001"><span
                    class="wpcf7-list-item-label">Sunt de acord cu prelucrarea datelor cu caracter personal, în conformitate cu prevederile Legii 677/2001</span></label></span></span></span><br>
            <a href="{% url 'contact:date' %}" target="_blank"
               style="font-size: 80%; text-decoration: underline; color:inherit;">Citiţi
                prelucrarea datelor cu caracter personal</a></p>
        <p></p>
</div>


<script>

function initMap() {
var home = {lat: 44.396814, lng: 26.118131};
var map = new google.maps.Map(document.getElementById('map'), {zoom: 17, center: home});
var marker = new google.maps.Marker({position: home, map: map});
}


</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB4OFdmtrM6UB3KKaGMJNJ1v3gSxGI5QRo&callback=initMap">
</script>

</body>
{% endblock %}

templates/contact/date_caracter_personal.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
    #top {
    height:100px;
    background:#000;
    }
    </style>
</head>
<body>
<div id="content" class="content-caracter" style="width:100%"><br><br>
    <h1 style="text-align:center">Prelucrarea datelor cu caracter personal</h1><br>
    <p style="text-align: justify;"><strong>Termeni generali</strong></p>
    <p style="text-align: justify;">Prelucrarea si stocarea datelor cu caracter personal este facuta in conditii de siguranta
        si in scopuri legitime legate in principal de desfasurarea activitatii de prestare a serviciilor comerciale,
        si in subsidiar, pentru reclama, maketing, publicitate, precum si servicii de statistica si informare.</p>
    <p style="text-align: justify;">Prin completarea formularului de contact va dati acordul in mod expres si neechivoc ca datele
        dumneavoastra cu caracter personal sa fie stocate si prelucrate de catre Urban Shoes SRL
        care va pastra confidentialitatea acestor informatii, cu exceptia informatiilor solicitate
        de autoritatile legale competente.</p>
    <p style="text-align: justify;"><strong>Scopul prelucrarii datelor cu caracter personal</strong></p>
    <p style="text-align: justify;">SC Urban Shoes SRL va prelucra datele personale cu urmatoarele scopuri:
        (i) comenzi si livrari produse afisate pe site-ul www.urbangear.ro;
        (ii) statistica; (iii) recuperare date de inregistrare (recuperare parola),
        si (iv) marketing si publicitate.</p>
    <p style="text-align: justify;"><strong>Persoanele imputernicite/Destinatari/Operator asociat:</strong></p>
        <p style="text-align: justify;">Datele dumneavoastra cu caracter personal pot fi prelucrate de catre urmatoarele persoane,
        cu respectarea intocmai a legislatiei privind protectia datelor cu caracter personal:</p>
    <p style="text-align: justify;">Datele personale prelucrate pot fi dezvaluite urmatorilor destinatari: (i) persoanei vizate
        (ii) reprezentantilor legali ai persoanei vizate (iii)  operatorilor de date
        (iv) partenerilor contractuali ai Urban Shoes SRL –
        Furnizorii de prestari servicii cum ar fi, dar fara a se limita la furnizori de servicii si sisteme IT,
        partenerii contractuali precum si toate societatile din aceste categorii de destinatari de la care
        Societatea va contracta servicii si produse si care au luat masuri adecvate de protectie,
        conform prevederilor legale, pentru a asigura ca acestia isi respecta obligatiile
        privind protectia datelor cu caracter personal;
        (v) alte companii din acelasi grup cu Urban Shoes SRL
        (vi) autoritatilor publice / autoritatea fiscala pe baza competentelor acestora prevazute de legea aplicabila,
        precum si oricare alte autoritati publice care pot solicita astfel de date in temeiul unor dispozitii legale</p>
    <p style="text-align: justify;"><strong>Transferul datelor cu caracter personal</strong></p>
    <p style="text-align: justify;">Datele personale pot fi dezvaluite unor terte parti, procesatoare de date personale,
        care se afla in strainatate, respectiv in oricare dintre tarile aflate in cadrul Uniunii Europene.
        De asemenea, anumite date personale pot fi dezvaluite in scopul raportarii actionarilor/conducerii
        Urban Shoes SRL.</p>
    <p style="text-align: justify;">In cazul in care datele dumneavoastra se vor transfera catre alte societati din alte tari,
        in vederea initierii, incheierii si dezvoltarii unor contracte si/sau proiecte cu o asemenea entitate,
        veti fi informat si se vor aplica garantiile prevazute de art. 44-49 din Regulamentul General privind
        protectia datelor.</p>
    <p style="text-align: justify;"><strong>Perioada de stocare a datelor cu caracter personal</strong></p>
    <p style="text-align: justify;">SC Urban Shoes SRL asigura confidentialitatea datelor cu caracter personal prelucrate in
        conformitate cu acordul exprimat de persoana fizica vizata si conform prevederilor legale.
        Accesul la informatiile tratate drept confidentiale va fi limitat la acele persoane,
        care prin natura activitatii desfasurate, este necesar sa ia cunostinta de aceste informatii in
        scopul ducerii la indeplinire a scopului, raporturilor juridice nascute in relatie cu
        Urban Shoes SRL. Aceste persoane sunt tinute sa respecte caracterul confidential al acestor informatii,
        asumandu-si la randul lor obligatia de a asigura si pastra confidentialitatea acestor date si
        informatii si de a le prelucra in conformitate cu cerintele legale.
        SC Urban Shoes SRL va respecta dispozitiile legale aplicabile domeniului de activitate,
        inclusiv ale Legii 95/2006 privind reforma in domeniul sanatatii in ceea ce priveste perioada de
        stocare a datelor cu caracter personal.</p>
    <p style="text-align: justify;"><strong>Securitatea datelor personale</strong></p>
    <p style="text-align: justify;">Conform Legii nr. 677/2001 pentru protectia persoanelor cu privire la prelucrarea
        datelor cu caracter personal si libera circulatie a acestor date, modificata si completata, si ale Legii nr.
        506/2004 privind prelucrarea datelor cu caracter personal si protectia vietii private in sectorul comunicatiilor
        electronice, informatiile furnizate de dumneavoastra vor fi folosite de URBAN GEAR exclusiv in scopul declarat
        al site-ului. Astfel, datele din formularul de comanda vor fi folosite numai pentru a va trimite confirmarea
        comenzilor, promotii, buletinele informative periodice (doar in masura in care sunteti de acord sa primiti acest
        gen de informatii) facturare si pentru livrarea comenzilor etc.</p>
    <p style="text-align: justify;">Nu sunteti obligat sa furnizati datele personale, insa refuzul face imposibila
        prelucrarea comenzii si derularea livrarii produselor. Informatiile inregistrate sunt destinate utilizarii de
        catre echipa URBAN GEAR.</p>
    <p style="text-align: justify;">Conform Legii nr. 677/2001, beneficiati de dreptul de acces, de interventie asupra
        datelor, dreptul de a nu fi supus unei decizii individuale si dreptul de a va adresa justitiei. De asemenea,
        aveti dreptul sa va opuneti prelucrarii datelor personale si sa solicitati stergerea datelor din baza noastra de
        date. Pentru exercitarea acestor drepturi, va puteti adresa catre SC URBAN SHOES SRL cu o cerere scrisa, datata
        si semnata. SC URBAN SHOES SRL se obliga sa nu faca publice sau sa nu vanda bazele de date continand informatii
        referitoare la datele personale ale clientilor sai. In cazul in care se va pune problema utilizarii datelor
        dumneavoastra in scopul realizarii unor campanii, vi se va cere acordul explicit.</p>
    <p style="text-align: justify;">URBAN GEAR nu trimite mesaje nesolicitate clientilor sai. Orice mesaj periodic
        trimis contine datele noastre de identificare, precum si o procedura valida de renuntare la subscriere.</p>
    <p style="text-align: justify;">Datele legate de plati/facturare vor fi stocate pe o perioada de 10 ani,
        conform Legii nr. 82/1991 privind contabilitatea;
    <p style="text-align: justify;">Datele inregistrarii apelurilor telefonice se vor stoca pe o perioada de 6 luni,
        respectiv in conformitate cu temeiurile prevazute de legislatia in vigoare,
        iar documentele incarcate pe site vor fi stocate pentru un termen de 30 de zile,
        ulterior acestui termen documentele vor fi sterse automat;

    <style>
                    .modal.fade.bs-example-modal-lg { z-index: 9999999 !important;}
.dropdown-menu { z-index: 99999991 !important; }
.prod-in-cos { font-size: 1.6em;    display: block;    padding-top: 10px; padding-left: 20px; }                    #mmosolution .modal-footer .mmosolution-button-full-cart-show{
                            margin-bottom: 10px !important;
                    }
                                        #dialog-popup-full-cart .btn-decrease {border-radius: 0 0 0 4px ; padding: 0px;  width: 50%;}
                    #dialog-popup-full-cart .btn-increase {border-radius: 0 0  4px 0 ;   padding: 0px;  width: 50%;}
                    #dialog-popup-full-cart .mmos_cart_action button{ padding: 0px !important;  width: 50% !important; margin:0 !important; float: left;   font-weight: bold}
                    #dialog-popup-full-cart .mmos_cart_action {}
                    #dialog-popup-full-cart .modal-footer {border-top: 0; margin-top: 0px;}
                    #dialog-popup-full-cart .modal-body{ padding: 10px;}
                    #dialog-popup-full-cart .mmos_quantity {
                        background: #F8F8F8;
                        min-width: 100%;
                        width: 100%;
                        border: 1px solid #eea236;
                        border-bottom: 0;
                        padding: 3px;
                        margin: -10px -10px 0 0;
                        margin-left: 0px;
                        margin-right: 0px;
                    }
					#dialog-popup-full-cart .btn-remove{padding: 5.5px 8px;}
					#popup-full-cart-heading i{font-size: 18px; }
				#mmosolution h4 {font-family: inherit }



    </style>
    <div id="mmosolution">
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="dialog-popup-full-cart"
             aria-labelledby="LargeModalLabel" aria-hidden="true">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">×</span></button>
            <div class="modal-dialog modal-lg" style="width:640px; max-width: 95%; orverflow: auto;">
                <div class="modal-content" style="background-color: #ffffff; ">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">×</span></button>
                        <h4 class="modal-title" id="popup-full-cart-heading"></h4>
                    </div>
                    <div class="modal-body" style="padding-top: 0px;padding-bottom: 0;">
                        <div class="mmos_name" style="word-wrap: break-word;">
                            <span class="prod-in-cos">Ai adaugat produse in cos.&nbsp;</span>
                            <hr>
                        </div>
                        <div class="">
                            <div class="col-md-12" id="popup-full-cart-form"></div>
                        </div>
                    </div>
                    <div class="modal-footer text-right" style="padding-bottom: 0px;">
                        <a class="btn btn-default mmosolution-button-full-cart-show" data-dismiss="modal">Continua
                            cumparaturile</a>
                        <a class="btn btn-default mmosolution-button-full-cart-show"
                           href="./index.php?route=checkout/cart"><i class="fa fa-share"></i> Vezi cos</a>
                        <a class="btn btn-success mmosolution-button-full-cart-show"
                           href="./index.php?route=checkout/checkout"><i class="fa fa-share"></i> Finalizare comanda</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">

            $(document).ajaxComplete(function( event, xhr, settings ) {
				 var res_action = settings.url.split("checkout/cart/add");
                if(res_action.length > 1 ){
                    var json = $.parseJSON(xhr.responseText);
                    if(!json['error'] ){

                            $('html, body').stop();
                            $('.alert-success').remove();
                            $.ajax({
                                type: 'get',
                                url: 'index.php?route=module/mmos_popup_full_cart',
                                dataType: 'json',
                                success: function(json) {
                                    $('#popup-full-cart-heading').html(json['heading']);
                                    $('#popup-full-cart-form').html(json['output']);
                                    $('#cart > button').html('<span id="cart-total"><i class="fa fa-shopping-cart"></i> ' + json['total'] + '</span>');
                                    $('#dialog-popup-full-cart').modal('show');
                                }
                            });

                    }
                }
            });


    </script>

</div>
</body>
</html>
{% endblock %}

templates/contact/succes.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style>
            #top{
    height:100px;
    }

    .center {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
    </style>
</head>
<body>
<div class="page page-fullwidth">
    <br><br><br>
    <div class="heading-wrapper">
        <div class="title" style="text-align:center"><h1><span>Mesajul dvs. a fost trimis cu succes!</span></h1></div>
    </div><br><br>
    <div class="center">
        <form action="{% url 'Produs:home' %}">
            <button type="submit" class="btn btn-outline-dark btn-lg" >
                <span class="glyphicon glyphicon-search"></span><strong> Inapoi la prima pagina </strong>
            </button>
        </form>
    </div>
</div>
<br><br><br><br><br><br><br>
</body>
{% endblock %}