MAIN/urls.py
from django.urls import path

from . import views

app_name = "Produs"

urlpatterns = [
    path('home/', views.Home.as_view(), name='home'),
    path('brands/', views.BrandsList.as_view(), name='brands'),
    path('cautare_avansata/', views.produs_list, name='avansata'),
]

URBAN_SHOES/urls.py
from django import views
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from MAIN.views import BrandsList

urlpatterns = [
    path('', include('MAIN.urls')),
    path('log_in/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path(r'', include('django.contrib.auth.urls'), {'next_page': 'login'}, name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path(r'', include('carts.urls')),
    path('', BrandsList.as_view()),
    path('', include('contact.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django import views
from django.urls import path
from .views import CreateNewAccount, termene, ModifyUserAccount

app_name = "accounts"

urlpatterns = [
    path('register/', CreateNewAccount.as_view(), name='new_user'),
    path('register/terms/', termene, name='terms'),
    path('register/updateProfile/<int:pk>/', ModifyUserAccount.as_view(), name='update_profile'),
]

carts/urls.py
from django.urls import path

from . import views
from .views import view_cart, add_to_cart, orders, CartUpdateView, remove_from_cart, ComenziList

app_name = "carts"

urlpatterns = [
    path('cos/', view_cart, name='cos'),
    path('cart/', add_to_cart, name='cart'),
    path('order/', orders, name='order'),
    path('history/<int:pk>/', CartUpdateView.as_view(), name='OrderUpdate'),
    path('remove/<int:pk>/', remove_from_cart, name='remove'),
    path('istoric/', ComenziList.as_view(), name='IstoricComenzi'),
]

contact/urls.py
from django import views
from django.urls import path

from contact.views import suport, contact, date_personale


app_name = "contact"

urlpatterns = [
    path('suport/', suport, name='suport'),
    path('contact/', contact, name='contact'),
    path('contact/date_caracter_personal/', date_personale, name='date'),
]

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% static "images" as baseUrl %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>URBAN_SHOES</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!--[if lte IE 6]>
    <style type="text/css" media="screen">.tabbed { height:420px; }</style><![endif]-->

</head>
<body>
<!-- Top -->
<div id="top">
    <div class="shell">
        <!-- Header -->
        <div id="header">
            <h1 id="logo"><a href="{% url 'Produs:home' %}">Urban Shoes</a></h1>
            <div id="navigation">
                <ul>
                    <li><a href="{% url 'Produs:home' %}">Acasa</a></li>
                    {% if request.user.is_authenticated is False%}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:update_profile' request.user.id %}">{{ request.user.first_name|upper }}</a></li>
                    <li><a href="{% url 'carts:IstoricComenzi' %}">Istoric Comenzi</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:new_user' %}">Creaza Cont</a></li>
                    {% endif %}
                    <li><a href="{% url 'contact:suport' %}">Suport</a></li>
                    <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="last"><a href="{% url 'logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- End Header -->
        <!-- Slider -->
        {% block content %}
        {% endblock %}
        <!-- End Slider -->
        <!-- Brands -->
        <br/><br/><br/><br/>
        <div class="brands">
            <h3 style="font-size:25px;">Brands</h3>
            <div class="logos">
                <a href="{% url 'Produs:brands' %}?cod=P"><img src="{% static 'css/images/puma.gif' %}" alt=""/></a>
                <a href="{% url 'Produs:brands' %}?cod=A"><img src="{% static 'css/images/adidas.gif' %}" alt=""/></a>
                <a href="{% url 'Produs:brands' %}?cod=B"><img src="{% static 'css/images/new_balance.gif' %}" alt=""/></a>
                <a href="{% url 'Produs:brands' %}?cod=N"><img src="{% static 'css/images/nike.gif' %}" alt=""/></a>
            </div>
        </div>
        <!-- End Brands -->
        <!-- Footer -->
        <div id="footer">
            <div class="left">
                <a href="{% url 'Produs:home' %}">Acasa</a> <span>|</span>
                <a href="{% url 'login' %}">Login</a> <span>|</span>
                <a href="{% url 'accounts:new_user' %}">Creaza Cont</a> <span>|</span>
                <a href="{% url 'contact:suport' %}">Suport</a> <span>|</span>
                <a href="{% url 'contact:contact' %}">Contact</a>
            </div>
            <div class="right"> Proiect SIIT - Mihai Ilie</div><br/>
        </div>
        <!-- End Footer -->
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/umd/carousel.js"></script>

<!--<script src="{% static 'js/jquery.jcarousel.pack.js' %}" type="text/javascript"></script>-->
<!--<script src="{% static '/js/jquery.slide.js' %}" type="text/javascript"></script>-->
<!--<script src="{% static '/js/jquery-func.js' %}" type="text/javascript"></script>-->
<script type="text/javascript"> var $jq1 = jQuery.noConflict(true);</script>


<!-- End Main -->
</body>
</html>

templates/brands.html
{% extends "base.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Brands</title>
    <style>

    #top{
    height:227px;
    }



    </style>
</head>

<div id="top">
    <div class="shell">
        <br><br><br><br>
        <h2 style="text-align:center; color:white">Sortare produse dupa brand</h2><br>
        <div id="container">
            <div class="tabbed">
                <!-- First Tab Content -->
                <div class="tab-content" style="display:block;">
                    <div class="items">
                        <ul>
                            {% for brands in object_list %}
                            <li>
                                <div class="image"><a href="#"><img src="{{ brands.img.url }}" alt="No picture"
                                                                    style="width:170px;height:150px;"/></a>
                                </div>
                                <p><strong>{{brands.brand}}</strong></p>
                                Culoare: <span style="font-size:14px">{{brands.culoare.upper}}</span><br/>
                                Cod: <span style="font-size:12px">{{brands.cod}}</span><br/>
                                Marimi:<br/>
                                {% for numar in brands.marimi %}
                                <span style="font-size:15px">{{numar}}&nbsp;</span>
                                {% endfor %}
                                <p class="price">Pret: <strong>{{brands.pret}}</strong></p>
                                <p>
                                    <a href="{% url 'carts:cart' %}?id_prod={{ brands.id }}" class="btn btn-dark">Adauga
                                        in cos</a>
                                </p>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/cautare_avansata.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Brands</title>
    <style>
    #top{
        height:100px;
    }



    </style>
</head>

<br><br><br>
<!--        <h2 style="text-align:center; color:dark">Cautare avansata</h2><br>-->
<!--        <div class="input-group">-->
<!--                        </div>-->
<!--                <form method="get">-->
<!--                    <div class="form-group">-->
<!--                        {% for var in filter.form %}}-->
<!--                            {{ var.brand }}-->
<!--                        {% endfor %}-->
<!--&lt;!&ndash;                    {{ filter.form.as_p }}&ndash;&gt;-->
<!--                    <input type="submit"/>-->
<!--                    </div>-->
<!--                </form>-->
<!--        </div>-->
<form method="get">
    <div class="well">
        <h2 style="margin-top: 0; text-align: center">Cautare avansata</h2><br>
        <div class="row">
            <div class="form-group col-sm-4 col-md-3">
                <label for="brand.id_for_label ">Brand</label>
                <!--                {{ filter.form.brand.label_tag}}-->
                {% render_field filter.form.brand class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
                <label for="gen.id_for_label ">Gen</label>
                <!--                {{ filter.form.gen.label_tag }}-->
                {% render_field filter.form.gen class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
                <label for="brand.id_for_label ">Culoare</label>
                <!--                {{ filter.form.culoare.label_tag }}-->
                {% render_field filter.form.culoare class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
                <label for="brand.id_for_label ">Marimi</label>
                <!--                {{ filter.form.marimi.label_tag }}-->
                {% render_field filter.form.marimi class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
                <label for="brand.id_for_label ">Cod</label>
                <!--                {{ filter.form.cod.label_tag }}-->
                {% render_field filter.form.cod class="form-control" %}
            </div>
            <div class="form-group col-sm-4 col-md-3">
                <label for="brand.id_for_label ">Pret</label>
                <!--                {{ filter.form.pret.label_tag }}-->
                {% render_field filter.form.pret class="form-control" %}
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-dark btn-lg" style="width:200px">
        <span class="glyphicon glyphicon-search"></span><strong> CAUTA </strong>
    </button>
    </div>
</form>


<div class="shell">
    <div id="container">
        <div class="tabbed">
            <div class="tab-content" style="display:block;">
                <div class="items">
                    <ul>
                        {% for obj in filter.qs %}
                        <li>
                            <div class="image"><a href="#"><img src="{{ obj.img.url }}" alt="No picture"
                                                                style="width:170px;height:150px;"/></a>
                            </div>
                            <p><strong>{{obj.brand}}</strong></p>
                            Culoare: <span style="font-size:14px">{{obj.culoare.upper}}</span><br/>
                            Cod: <span style="font-size:12px">{{obj.cod}}</span><br/>
                            Marimi:<br/>
                            {% for numar in obj.marimi %}
                            <span style="font-size:15px">{{numar}}&nbsp;</span>
                            {% endfor %}
                            <p class="price">Pret: <strong>{{obj.pret}}</strong></p>
                            <p>
                                <a href="{% url 'carts:cart' %}?id_prod={{ obj.id }}" class="btn btn-dark">Adauga
                                    in cos</a>
                            </p>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="cl">&nbsp;</div>
                    <br/>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
{% static "images" as baseUrl %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>URBAN_SHOES</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <!--[if lte IE 6]>
    <style type="text/css" media="screen">.tabbed { height:420px; }</style><![endif]-->
    <style type="text/css">
        .cart { float:left; position:relative; top:3px; width:160px; }
    </style>
</head>
<body>
<!-- Top -->
<div id="top" style="height:488px; background:#000;">
    <div class="shell">
        <!-- Header -->
        <div id="header">
            <h1 id="logo"><a href="{% url 'Produs:home' %}">Urban Shoes</a></h1>
            <div id="navigation">
                <ul>
                    <li><a href="{% url 'Produs:home' %}">Acasa</a></li>
                    {% if request.user.is_authenticated is False%}
                    <li><a href="{% url 'login' %}">Login</a></li>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:update_profile' request.user.id %}">{{ request.user.first_name|upper }}</a></li>
                    <li><a href="{% url 'carts:IstoricComenzi' %}">Istoric Comenzi</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:new_user' %}">Creaza Cont</a></li>
                    {% endif %}
                    <li><a href="{% url 'contact:suport' %}">Suport</a></li>
                    <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="last"><a href="{% url 'logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
        <!-- End Header -->
        <!-- Slider -->
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="{% static 'css/images/slide1.jpg' %}" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="{% static 'css/images/slide2.jpg' %}" alt="Second slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <!-- End Slider -->
    </div>
</div>
<!-- Top -->
<!-- Main -->
<div id="main">

    <div class="shell">
        <!-- Search, etc -->
        <div class="options">
            <div class="search">
<!--                <form action="#" method="post">-->
<!--                  <span class="field">-->
<!--                    <input type="text" class="blink" value="CAUTARE" title="SEARCH"/>-->
<!--                  </span>-->
<!--                    <input type="text" class="search-submit" value="GO"/>-->
<!--                </form>-->
            </div>
            <span class="left"><a href="{% url 'Produs:avansata' %}"><strong>CAUTARE AVANSATA</strong></a></span>
            {% if request.user.is_authenticated %}
            <div class="right" >
                <div class="cart" >
                <a href="{% url 'carts:cos' %}" class="cart-ico"></a>
                    <strong style="font-size:15px">{{ pret }} RON</strong>
                </div>
                <span class="left more-links"> <a href="{% url 'carts:cos' %}">Finalizeaza Comanda</a></span>
            </div>
            {% endif %}
        </div>
        <!-- End Search, etc -->
        <!-- Content -->
        <div id="content">

            <!-- Tabs -->
            <div class="tabs">

                <ul>
                    {% if gen == 'COPII' %}
                    <li><a href="{% url 'Produs:home' %}?var=BARBATI"><span>BARBATI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=FEMEI"><span>FEMEI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=COPII" class="active"><span>COPII</span></a></li>
                    {% elif gen == 'FEMEI' %}
                    <li><a href="{% url 'Produs:home' %}?var=BARBATI"><span>BARBATI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=FEMEI" class="active"><span>FEMEI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=COPII"><span>COPII</span></a></li>
                    {% else %}
                    <li><a href="{% url 'Produs:home' %}?var=BARBATI" class="active"><span>BARBATI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=FEMEI"><span>FEMEI</span></a></li>
                    <li><a href="{% url 'Produs:home' %}?var=COPII"><span>COPII</span></a></li>
                    {% endif %}
                </ul>
            </div>
            <!-- Filter -->
            <!-- Container -->
            <div id="container">
                <div class="tabbed">
                    <div class="tab-content" style="display:block;">
                        <div class="items">
                            <ul>
                                {% for prod in orice %}
                                <li>
                                    <div class="image"><a href="#"><img src="{{ prod.img.url }}" alt="No picture"
                                                                        style="width:170px;height:150px;"/></a>
                                    </div>
                                    <p><strong>{{prod.brand}}</strong></p>
                                    Culoare: <span style="font-size:14px">{{prod.culoare.upper}}</span><br/>
                                    Cod: <span style="font-size:12px">{{prod.cod}}</span><br/>
                                    Marimi:<br/>
                                    {% for numar in prod.marimi %}
                                    <span style="font-size:15px">{{numar}}&nbsp;</span>
                                    {% endfor %}
                                    <p class="price">Pret: <strong>{{prod.pret}}</strong></p>
                                    {% if request.user.is_authenticated %}
                                    <p>
                                        <a href="{% url 'carts:cart' %}?id_prod={{ prod.id }}" class="btn btn-dark">Adauga
                                            in cos</a>
                                    </p>
                                    {% endif %}
                                </li>
                                {% endfor %}
                            </ul>
                            <div class="cl">&nbsp;</div>
                        </div>
                    </div>
                </div>
                <!-- Brands -->
                <br/><br/><br/><br/>
                <div class="brands">
                    <h3 style="font-size:25px;">Brands</h3>
                    <div class="logos">
                        <a href="{% url 'Produs:brands' %}?cod=P"><img src="{% static 'css/images/puma.gif' %}" alt=""/></a>
                        <a href="{% url 'Produs:brands' %}?cod=A"><img src="{% static 'css/images/adidas.gif' %}"
                                                                       alt=""/></a>
                        <a href="{% url 'Produs:brands' %}?cod=B"><img src="{% static 'css/images/new_balance.gif' %}"
                                                                       alt=""/></a>
                        <a href="{% url 'Produs:brands' %}?cod=N"><img src="{% static 'css/images/nike.gif' %}" alt=""/></a>
                    </div>
                </div>
                <!-- End Brands -->
                <!-- Footer -->
                <div id="footer">
                    <div class="left">
                        <a href="{% url 'Produs:home' %}">Acasa</a> <span>|</span>
                        <a href="{% url 'login' %}">Login</a> <span>|</span>
                        <a href="{% url 'accounts:new_user' %}">Creaza Cont</a> <span>|</span>
                        <a href="{% url 'contact:suport' %}">Suport</a> <span>|</span>
                        <a href="{% url 'contact:contact' %}">Contact</a>
                    </div>
                    <div class="right"> Proiect SIIT - Mihai Ilie</div>
                </div>
                <!-- End Footer -->
            </div>
            <!-- End Container -->
        </div>
        <!-- End Content -->
    </div>
</div>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/umd/carousel.js"></script>

<script type="text/javascript">
    $('.carousel').carousel('cycle'{interval:1000});
</script>

<!--<script src="{% static 'js/jquery.jcarousel.pack.js' %}" type="text/javascript"></script>-->
<!--<script src="{% static '/js/jquery.slide.js' %}" type="text/javascript"></script>-->
<!--<script src="{% static '/js/jquery-func.js' %}" type="text/javascript"></script>-->
<script type="text/javascript"> var $jq1 = jQuery.noConflict(true);</script>


<!-- End Main -->
</body>
</html>